version: '3'
services:
  db:
    image: "postgres:11"
    container_name: "my_postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xendittest
      POSTGRES_DB: xendit
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ".:/app"
    command: npm start

